import {SEEDS,CATEGORIES,seedRole,guideProgress} from './catalog.js';
export function createCatalog({choose,thumbnail}){
  let category='flora',stamp='';const cache=new Map();
  const tabs=document.getElementById('creation-tabs'),cards=document.getElementById('seed-catalog'),tip=document.getElementById('seed-tip'),guide=document.getElementById('creation-guide');
  function selectCategory(key){category=key;render();choose([Object.keys(SEEDS).find(id=>SEEDS[id].category===key)]);}
  for(const [key,def]of Object.entries(CATEGORIES)){const b=document.createElement('button');b.type='button';b.role='tab';b.id='category-'+key;b.dataset.category=key;b.setAttribute('aria-controls','seed-catalog');b.textContent=def.label;b.onclick=()=>selectCategory(key);tabs.append(b);}
  function render(){for(const b of tabs.children){b.setAttribute('aria-selected',String(b.dataset.category===category));b.classList.toggle('active',b.dataset.category===category);}cards.setAttribute('aria-labelledby','category-'+category);document.getElementById('category-hint').textContent=CATEGORIES[category].hint;cards.replaceChildren();
    for(const [id,def]of Object.entries(SEEDS)){if(def.category!==category)continue;const b=document.createElement('button');b.type='button';b.className='seed-card';b.dataset.seed=id;b.setAttribute('aria-label',def.name+'. '+def.desc);b.title=def.desc;b.style.setProperty('--seed-color',def.color);const img=document.createElement('img');img.alt='';img.width=128;img.height=100;if(!cache.has(id))cache.set(id,thumbnail(id));img.src=cache.get(id);const name=document.createElement('strong');name.textContent=def.name;const desc=document.createElement('span');desc.textContent=def.desc;b.append(img,name,desc);b.onclick=()=>choose([id]);cards.append(b);}}
  function update(mix,world){const role=seedRole({seeds:mix});if(role&&SEEDS[role].category!==category){category=SEEDS[role].category;render();}for(const b of cards.children){const chosen=b.dataset.seed===role;b.classList.toggle('chosen',chosen);b.setAttribute('aria-pressed',String(chosen));}tip.textContent=role?SEEDS[role].tip:'Mix freely, or pick a starting seed above.';
    if(world){const progress=guideProgress(world),next=JSON.stringify(progress);if(next!==stamp){stamp=next;guide.replaceChildren();for(const step of progress){const b=document.createElement('button');b.type='button';b.className=step.done?'complete':'';b.textContent=(step.done?'✓ ':'○ ')+step.label;const small=document.createElement('small');small.textContent=step.detail;b.append(small);b.onclick=()=>selectCategory(step.category);guide.append(b);}}}}
  render();return {update,selectCategory};
}
