import {foliageGeometry} from './foliage.js';
import * as T from 'three';
import {PLANET_RADIUS as P,normalAt,surfaceAt,coordsOf,groundAt,elevationNormal,noise,landAt,wrapped,LATITUDE_LIMIT} from './planet.js';
import {organism,disposeOrganism,signature} from './organisms.js';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const Y=new T.Vector3(0,1,0),Z=new T.Vector3(0,0,1),tmp=new T.Object3D();
function frameAt(x,z){const a=x/P,b=z/P;return {up:new T.Vector3(...normalAt(x,z)),east:new T.Vector3(Math.cos(a),0,-Math.sin(a)),south:new T.Vector3(Math.sin(a)*Math.sin(b),-Math.cos(b),Math.cos(a)*Math.sin(b))};}
function landColor(n,h){const moisture=noise(n.x*13+4,n.y*13+7,n.z*13+2),detail=noise(n.x*140,n.y*140,n.z*140);const c=new T.Color(h<.8?'#c5bf8a':h<2?'#9fa86d':h>24?'#bcc6bf':h>14?'#81846a':moisture<.4?'#819447':'#497649');c.multiplyScalar(.87+detail*.22);if(Math.abs(n.y)>.91)c.lerp(new T.Color('#e1e9dc'),.8);return c;}
export class View{
 constructor(container,onTap,onDrag){
  this.container=container;this.scene=new T.Scene();this.scene.background=new T.Color('#abcbd6');this.scene.fog=new T.FogExp2('#abcbd6',.008);
  this.renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.25:1.5));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;container.appendChild(this.renderer.domElement);
  this.camera=new T.PerspectiveCamera(43,1,.08,8000);this.target=new T.Vector3();this.cx=0;this.cz=0;this.yaw=.6;this.pitch=.39;this.distance=42;this.desiredDistance=42;this.followId=null;this.entities=new Map();this.patches=new Map();this.bubbles=new Map();this.selected=null;this.tool='inspect';this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  this.scene.add(new T.HemisphereLight('#d7e8ed','#546135',1.3));this.sun=new T.DirectionalLight('#fff0cf',2.6);this.sun.castShadow=true;this.sun.shadow.mapSize.set(innerWidth<700?1024:2048,innerWidth<700?1024:2048);Object.assign(this.sun.shadow.camera,{left:-32,right:32,top:32,bottom:-32,near:1,far:220});this.sun.shadow.normalBias=.06;this.sun.shadow.bias=-.00008;this.scene.add(this.sun,this.sun.target);
  this.makePlanet();this.makeNature();this.makeClouds();
  this.selection=new T.Mesh(new T.RingGeometry(.9,.93,64),new T.MeshBasicMaterial({color:'#e8d7a6',transparent:true,opacity:.85,side:T.DoubleSide,depthWrite:false}));this.selection.visible=false;this.scene.add(this.selection);
  this.cursor=new T.Mesh(new T.RingGeometry(.6,.65,48),new T.MeshBasicMaterial({color:'#eff2bc',transparent:true,opacity:.75,side:T.DoubleSide,depthWrite:false}));this.cursor.visible=false;this.scene.add(this.cursor);
  this.ray=new T.Raycaster();this.pointer=new T.Vector2();this.bind(onTap,onDrag);this.resize();this.cameraPosition();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(container);
 }
 terrainMaterial(){
  const material=new T.MeshStandardMaterial({vertexColors:true,roughness:1});
  material.onBeforeCompile=shader=>{shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 terrainPoint;').replace('#include <begin_vertex>','#include <begin_vertex>\nterrainPoint=position;');shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>
varying vec3 terrainPoint;
float grain(vec3 p){p=fract(p*.3183099+vec3(.11,.17,.13));p*=17.;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}
float turf(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(grain(i),grain(i+vec3(1,0,0)),f.x),mix(grain(i+vec3(0,1,0)),grain(i+vec3(1,1,0)),f.x),f.y),mix(mix(grain(i+vec3(0,0,1)),grain(i+vec3(1,0,1)),f.x),mix(grain(i+vec3(0,1,1)),grain(i+vec3(1,1,1)),f.x),f.y),f.z);}
`).replace('#include <color_fragment>',`#include <color_fragment>
float mottles=turf(terrainPoint*1.5)*.45+turf(terrainPoint*8.)*.25+turf(terrainPoint*35.)*.3;
diffuseColor.rgb*=.65+mottles*.63;
`);};return material;
 }
 makePlanet(){
  const geo=new T.SphereGeometry(P,512,256),p=geo.attributes.position,colors=[],n=new T.Vector3();for(let i=0;i<p.count;i++){n.fromBufferAttribute(p,i).normalize();const h=elevationNormal(n.x,n.y,n.z);p.setXYZ(i,n.x*(P+h),n.y*(P+h),n.z*(P+h));const c=landColor(n,h);colors.push(c.r,c.g,c.b);}geo.setAttribute('color',new T.Float32BufferAttribute(colors,3));geo.computeVertexNormals();
  this.ground=new T.Mesh(geo,this.terrainMaterial());this.ground.receiveShadow=true;this.scene.add(this.ground);
  const ocean=new T.Mesh(new T.SphereGeometry(P+.08,192,96),new T.MeshStandardMaterial({color:'#358898',roughness:.28,metalness:.25}));ocean.receiveShadow=true;this.scene.add(ocean);this.ocean=ocean;
  const atmosphereMat=new T.ShaderMaterial({uniforms:{color:{value:new T.Color('#79b8df')}},vertexShader:'varying vec3 vN; varying vec3 vP; void main(){vN=normalize(mat3(modelMatrix)*normal);vP=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(vP,1.);}',fragmentShader:'uniform vec3 color;varying vec3 vN;varying vec3 vP;void main(){float f=pow(max(0.,dot(normalize(cameraPosition-vP),vN)+.15),3.);gl_FragColor=vec4(color,min(.6,f*.8));}',side:T.BackSide,transparent:true,blending:T.AdditiveBlending,depthWrite:false});this.atmosphere=new T.Mesh(new T.SphereGeometry(P+5,96,48),atmosphereMat);this.scene.add(this.atmosphere);
  const starPos=[];for(let i=0;i<1600;i++){const y=1-2*(i+.5)/1600,a=i*2.399,r=Math.sqrt(1-y*y);starPos.push(Math.cos(a)*r*5500,y*5500,Math.sin(a)*r*5500);}const starsGeo=new T.BufferGeometry();starsGeo.setAttribute('position',new T.Float32BufferAttribute(starPos,3));this.stars=new T.Points(starsGeo,new T.PointsMaterial({color:'#e9ebef',size:1.25,sizeAttenuation:true,transparent:true,opacity:1,fog:false}));this.scene.add(this.stars);
 }
 makeNature(){
  this.nature=new T.Group();this.scene.add(this.nature);const sites=[];
  // Global woodland plus a denser local biome; all positions use shared elevation.
  for(let i=0;i<9200;i++){const y=1-2*(i+.5)/9200,a=i*2.39996323,c=Math.sqrt(1-y*y),n={x:Math.cos(a)*c,y,z:Math.sin(a)*c};const pos=coordsOf(n),h=groundAt(pos.x,pos.z);if(h<1.8||h>18||noise(n.x*21+12,n.y*21+3,n.z*21+8)<.49)continue;sites.push({...pos,h,scale:1.2+noise(n.x*55,n.y*55,n.z*55)*1.8,kind:i%4});}
  for(let i=0;i<900;i++){const a=i*2.3999,r=8+Math.sqrt(i/900)*88,x=Math.cos(a)*r,z=Math.sin(a)*r;if(!landAt(x,z)||noise(x*.07+5,z*.07,3)<.45)continue;sites.push({x,z,h:groundAt(x,z),scale:1.2+noise(x,z,4)*2,kind:i%4});}
  const trunkGeo=new T.CylinderGeometry(.06,.14,1,6),crownGeo=foliageGeometry(),trunks=new T.InstancedMesh(trunkGeo,new T.MeshStandardMaterial({color:'#6d6950',roughness:1}),sites.length),crowns=new T.InstancedMesh(crownGeo,new T.MeshStandardMaterial({color:'#7a965b',roughness:1}),sites.length*3);trunks.receiveShadow=true;crowns.receiveShadow=true;crowns.castShadow=true;
  const color=new T.Color();sites.forEach((s,i)=>{const up=new T.Vector3(...normalAt(s.x,s.z)),pos=new T.Vector3(...surfaceAt(s.x,s.z)),q=new T.Quaternion().setFromUnitVectors(Y,up);tmp.position.copy(pos).addScaledVector(up,s.scale*.65);tmp.quaternion.copy(q);tmp.scale.set(s.scale,s.scale*1.3,s.scale);tmp.updateMatrix();trunks.setMatrixAt(i,tmp.matrix);for(let j=0;j<3;j++){tmp.position.copy(pos).addScaledVector(up,s.scale*(1.05+j*.3));tmp.scale.set(s.scale*(.78-j*.13),s.scale*(.5+j*.08),s.scale*(.74-j*.12));tmp.updateMatrix();crowns.setMatrixAt(i*3+j,tmp.matrix);color.set(s.kind===0?'#91a877':s.kind===1?'#66815b':s.kind===2?'#9d9973':'#597e69').multiplyScalar(.86+noise(s.x,s.z,j)*.27);crowns.setColorAt(i*3+j,color);}});trunks.instanceMatrix.needsUpdate=true;crowns.instanceMatrix.needsUpdate=true;this.nature.add(trunks,crowns);
  const count=4000,grass=new T.InstancedMesh(new T.ConeGeometry(.12,.65,3),new T.MeshStandardMaterial({color:'#aab879',roughness:1}),count);let used=0;for(let i=0;i<count;i++){const a=i*2.399,r=Math.sqrt(i/count)*80,x=Math.cos(a)*r,z=Math.sin(a)*r;if(!landAt(x,z))continue;const up=new T.Vector3(...normalAt(x,z));tmp.position.set(...surfaceAt(x,z,.2));tmp.quaternion.setFromUnitVectors(Y,up);const size=.6+noise(x,z,7);tmp.scale.set(size,size,size);tmp.updateMatrix();grass.setMatrixAt(used++,tmp.matrix);}grass.count=used;grass.receiveShadow=true;this.nature.add(grass);
  const rocks=new T.InstancedMesh(new T.DodecahedronGeometry(1,0),new T.MeshStandardMaterial({color:'#919780',roughness:1}),240);for(let i=0;i<240;i++){const a=i*2.399,r=5+Math.sqrt(i/240)*75,x=Math.sin(a)*r,z=Math.cos(a)*r;tmp.position.set(...surfaceAt(x,z));tmp.quaternion.setFromUnitVectors(Y,new T.Vector3(...normalAt(x,z)));const s=.25+noise(x,z,3)*.8;tmp.scale.set(s,s*.6,s*.8);tmp.updateMatrix();rocks.setMatrixAt(i,tmp.matrix);}rocks.receiveShadow=true;this.nature.add(rocks);
 }
 makeClouds(){
  const canvas=document.createElement('canvas');canvas.width=128;canvas.height=128;const c=canvas.getContext('2d'),grad=c.createRadialGradient(64,64,2,64,64,63);grad.addColorStop(0,'rgba(255,255,255,.62)');grad.addColorStop(.4,'rgba(255,255,255,.25)');grad.addColorStop(1,'rgba(255,255,255,0)');c.fillStyle=grad;c.fillRect(0,0,128,128);const texture=new T.CanvasTexture(canvas);this.clouds=new T.Group();for(let i=0;i<110;i++){const x=wrapped(i*27),z=Math.sin(i*1.62)*P*1.25;const s=new T.Sprite(new T.SpriteMaterial({map:texture,transparent:true,opacity:.5,depthWrite:false,fog:true}));s.position.set(...normalAt(x,z).map(v=>v*(P+24)));s.scale.set(19+i%5*4,7+i%4*3,1);this.clouds.add(s);}this.scene.add(this.clouds);
 }
 resize(){const w=this.container.clientWidth||innerWidth,h=this.container.clientHeight||innerHeight;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);}
 cameraPosition(){
  const f=frameAt(this.cx,this.cz),pos=new T.Vector3(...surfaceAt(this.cx,this.cz,this.targetHeight||.9)),orbit=clamp((this.distance-160)/1100,0,1);this.target.copy(pos).multiplyScalar(1-orbit);const pitch=this.pitch+(Math.PI/2-this.pitch)*orbit;const dir=f.east.clone().multiplyScalar(Math.sin(this.yaw)*Math.cos(pitch)).addScaledVector(f.south,Math.cos(this.yaw)*Math.cos(pitch)).addScaledVector(f.up,Math.sin(pitch));this.camera.position.copy(this.target).addScaledVector(dir,this.distance);this.camera.up.copy(f.up.clone().lerp(new T.Vector3(0,1,0),orbit*.97).normalize());this.camera.lookAt(this.target);this.camera.updateMatrixWorld();
  const sky=new T.Color('#add5e6'),space=new T.Color('#081726'),air=clamp((this.distance-130)/700,0,1);this.scene.background.copy(sky.lerp(space,air));this.scene.fog.color.copy(this.scene.background);this.scene.fog.density=.0048*(1-air);this.nature.visible=this.distance<230;this.stars.visible=air>.2;this.atmosphere.visible=this.distance>600;this.clouds.visible=this.distance>13;
  this.sun.position.copy(pos).addScaledVector(f.up,100).addScaledVector(f.east,-70).addScaledVector(f.south,45);this.sun.target.position.copy(pos);this.sun.shadow.camera.updateProjectionMatrix();this.renderer.shadowMap.enabled=this.distance<120;
  const label=document.getElementById('camera-scale');if(label)label.textContent=this.distance>800?'PLANET':this.distance>80?'REGION':this.distance>18?'ECOSYSTEM':'CREATURE';
 }
 zoom(factor){this.desiredDistance=clamp(this.desiredDistance*factor,3.5,2200);}
 orbit(){this.followId=null;this.desiredDistance=1850;}
 reset(){this.targetHeight=1.4;this.followId=null;this.cx=0;this.cz=0;this.cx=-3;this.cz=-4;this.yaw=1.65;this.pitch=.48;this.desiredDistance=innerWidth<700?74:63;this.cameraPosition();}
 focus(e){this.targetHeight=e.kind==='home'?(e.phase==='city'?4.5:2):1.8;this.followId=e.id;this.cx=e.x;this.cz=e.z;this.desiredDistance=e.phase==='city'?29:e.kind==='home'?12:8.5;this.pitch=.2;this.yaw=e.heading+Math.PI/2+.5;}
 locate(x,z,d=32){this.targetHeight=1.2;this.followId=null;this.cx=x;this.cz=z;this.desiredDistance=d;this.pitch=.4;}
 orient(mesh,x,z,lift=0){mesh.position.set(...surfaceAt(x,z,lift));const f=frameAt(x,z),basis=new T.Matrix4().makeBasis(f.east,f.up,f.south);mesh.quaternion.setFromRotationMatrix(basis);}
 sync(world,selected){
  this.selected=selected;const ids=new Set(world.state.entities.map(e=>e.id));for(const [id,m]of this.entities)if(!ids.has(id)){this.scene.remove(m);disposeOrganism(m);this.entities.delete(id);this.bubbles.get(id)?.remove();this.bubbles.delete(id);}
  for(const e of world.state.entities){const key=signature(e);let m=this.entities.get(e.id);if(!m||m.userData.key!==key){if(m){this.scene.remove(m);disposeOrganism(m);}m=organism(e);m.userData.key=key;m.userData.previous={x:e.x,z:e.z};this.scene.add(m);this.entities.set(e.id,m);}}
  const patches=new Set(world.state.patches.map(p=>p.id));for(const[id,m]of this.patches)if(!patches.has(id)){this.scene.remove(m);m.geometry.dispose();m.material.dispose();this.patches.delete(id);}
  for(const p of world.state.patches)if(!this.patches.has(p.id)){const m=new T.Mesh(new T.CircleGeometry(p.r,40),new T.MeshStandardMaterial({color:{water:'#59b8c9',fire:'#ee9a47',thorns:'#66673e'}[p.type],roughness:.28,transparent:true,opacity:.55,side:T.DoubleSide,depthWrite:false}));m.position.set(...surfaceAt(p.x,p.z,.12));m.quaternion.setFromUnitVectors(Z,new T.Vector3(...normalAt(p.x,p.z)));this.scene.add(m);this.patches.set(p.id,m);}
 }
 render(world,time){
  const follow=world.find(this.followId);if(follow){this.cx=follow.x;this.cz=follow.z;}this.distance+=(this.desiredDistance-this.distance)*(this.reduced?1:.12);this.cameraPosition();this.nature.visible=this.distance<230&&world.state.scenario==="living-world";const selected=world.find(this.selected);this.selection.visible=!!selected&&this.distance<100;if(selected){this.selection.position.set(...surfaceAt(selected.x,selected.z,.16));this.selection.quaternion.setFromUnitVectors(Z,new T.Vector3(...normalAt(selected.x,selected.z)));this.selection.scale.setScalar(selected.phase==='city'?selected.size*3:selected.size*1.25);}
  let spoken=0;
  for(const e of world.state.entities){const m=this.entities.get(e.id);if(!m)continue;this.orient(m,e.x,e.z,.04);const facing=new T.Quaternion().setFromAxisAngle(Y,Math.PI/2+e.heading);m.quaternion.multiply(facing);const size=(e.age<3?.08+e.age*.065:e.age<14?.28+(e.age-3)/11*.72:1)*e.size;m.scale.setScalar(size);const near=m.position.distanceTo(this.camera.position)<(e.phase==='city'?520:190);m.visible=near;
   const movement=Math.hypot(e.x-m.userData.previous.x,e.z-m.userData.previous.z);m.userData.moving=(m.userData.moving||0)*.92+movement*3;m.userData.previous={x:e.x,z:e.z};const walk=e.control!=='rooted'&&m.userData.moving>.004;
   if(!this.reduced&&near){m.userData.body.position.y=Math.sin(time*1.5+e.motion)*.018;if(m.userData.head){m.userData.head.rotation.x=Math.sin(time*1.3+e.motion)*.035+(e.activity==='grazing'?.28:0);m.userData.head.rotation.y=Math.sin(time*.8+e.motion)*.09;}if(m.userData.tail)m.userData.tail.rotation.y=Math.sin(time*2+e.motion)*.19;m.userData.legs.forEach((leg,i)=>{leg.rotation.x=walk?Math.sin(world.state.time*(e.phase==='city'?1.1:4)+i*Math.PI*.8+e.motion)*.25:Math.sin(time+e.motion+i)*.012;});if(m.userData.residents)m.userData.residents.children.forEach((p,i)=>{const a=p.userData.angle+world.state.time*.13;p.position.x=Math.cos(a)*p.userData.radius;p.position.z=Math.sin(a)*p.userData.radius;p.rotation.y=-a;});}
   const text=e.speechUntil>world.state.time?e.speech:null;const show=!!text&&near&&this.distance<55&&(e.id===this.selected||spoken<3);if(show){spoken++;let b=this.bubbles.get(e.id);if(!b){b=document.createElement('div');b.className='speech';document.getElementById('speech-layer').append(b);this.bubbles.set(e.id,b);}b.textContent=text;const p=new T.Vector3(...surfaceAt(e.x,e.z,m.userData.height*size+.45)).project(this.camera);b.style.left=(p.x+1)*.5*innerWidth+'px';b.style.top=(1-p.y)*.5*innerHeight+'px';b.hidden=p.z<0||p.z>1||Math.abs(p.x)>1||Math.abs(p.y)>1;}else if(this.bubbles.has(e.id)){this.bubbles.get(e.id).remove();this.bubbles.delete(e.id);}
  }
  for(const p of world.state.patches){const m=this.patches.get(p.id);if(m)m.material.opacity=Math.min(.55,p.life/10);}
  if(!this.reduced)this.clouds.rotation.y=time*.0008;this.renderer.render(this.scene,this.camera);
 }
 point(clientX,clientY){const r=this.renderer.domElement.getBoundingClientRect();this.pointer.set((clientX-r.left)/r.width*2-1,1-(clientY-r.top)/r.height*2);this.ray.setFromCamera(this.pointer,this.camera);const hit=this.ray.intersectObject(this.ground,false)[0];return hit?coordsOf(hit.point):null;}
 hit(clientX,clientY){this.point(clientX,clientY);this.scene.updateMatrixWorld(true);const hits=this.ray.intersectObjects([...this.entities.values()].filter(o=>o.visible),true);if(!hits.length)return null;let o=hits[0].object;while(o&&!o.userData.entityId)o=o.parent;return o?.userData.entityId||null;}
 bind(onTap,onDrag){const c=this.renderer.domElement,pointers=new Map();let start=null,last=null,pinch=0,moved=false,pan=false;
  c.addEventListener('contextmenu',e=>e.preventDefault());c.addEventListener('pointerdown',e=>{c.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1){start={x:e.clientX,y:e.clientY};last={...start};moved=false;pan=e.button===2||e.shiftKey;}else{moved=true;const p=[...pointers.values()];pinch=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);}});
  c.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)){if(this.tool==='inspect'){this.cursor.visible=false;return;}const pt=this.point(e.clientX,e.clientY);this.cursor.visible=!!pt&&landAt(pt.x,pt.z);if(this.cursor.visible){this.cursor.position.set(...surfaceAt(pt.x,pt.z,.1));this.cursor.quaternion.setFromUnitVectors(Z,new T.Vector3(...normalAt(pt.x,pt.z)));this.cursor.scale.setScalar(['love','fear','rain','mutate'].includes(this.tool)?7:1);}return;}pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const p=[...pointers.values()],n=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(pinch>0)this.zoom(pinch/n);pinch=n;moved=true;return;}if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>6)moved=true;if(moved&&last){const dx=e.clientX-last.x,dy=e.clientY-last.y;if(pan||this.distance>800){this.followId=null;const rate=this.distance*.0018;this.cx=wrapped(this.cx-dx*rate);this.cz=clamp(this.cz+dy*rate,-LATITUDE_LIMIT,LATITUDE_LIMIT);}else{this.yaw-=dx*.006;this.pitch=clamp(this.pitch+dy*.004,.1,1.45);}onDrag?.();}last={x:e.clientX,y:e.clientY};});
  c.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);if(!moved&&start&&!pan){const pt=this.point(e.clientX,e.clientY);if(pt){if(this.distance>180)this.locate(pt.x,pt.z,42);else onTap(pt,this.hit(e.clientX,e.clientY));}}if(!pointers.size){start=null;last=null;}else moved=true;});c.addEventListener('pointercancel',()=>{pointers.clear();start=null;moved=true;});c.addEventListener('pointerleave',()=>{this.cursor.visible=false;});c.addEventListener('wheel',e=>{e.preventDefault();this.zoom(Math.exp(e.deltaY*.0012));},{passive:false});c.addEventListener('dblclick',e=>{const id=this.hit(e.clientX,e.clientY);if(id)this.followId=id;else{const p=this.point(e.clientX,e.clientY);if(p)this.locate(p.x,p.z,16);}});
 }
}
